
server:
  port: 8888


spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@oracle.coffit.site:1521:xe
    username: C##HOT6
    password: HOT6
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      location: C:\DEV\04_project\HotsixBoot
#  web:
#    resources:
#      static-locations: classpath:/productimgs/

  ## jpa config
  jpa:
    generate-ddl: false
    show-sql: true
    database: oracle
    properties:
      hibernate:
        '[format_sql]': true



jwt:
  secret: V2UgYXJlIFRpdGFucyBhdGUgaG90NiEgT3VyIHBhc3Npb24gY29tZSBmcm9tIGhvdDYh

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html


image:


#  add-resource-locations: classpath:/static/productimgs/
#  add-resource-handler: /productimgs/**


#  image-dir: src/main/resources/static/productimgs
#  image-url: http://localhost:8080/productimgs/

# Logging Level
logging:
  level:
    root: info
